# Generated by Django 3.1.7 on 2021-05-02 05:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomcode',
            field=models.CharField(default=api.models.code_gen, max_length=8, unique=True),
        ),
    ]
